public enum CollisionLayers
{
    Enviroment = 1,
    Player,
    PlayerCollectionArea,
    PlayerHitBox,
    PlayerRegularHurtBox,
    PlayerSpecialHurtBox,
    PlayerShield,
    PlayerShieldHitBox,
    PlayerShieldHurtBox,
    WordEnemy,
    MeteorEnemy,
    RegularEnemy,
    WordEnemyHurtBox,
    MeteorEnemyHurtBox,
    RegularEnemyHurtBox,
    WordEnemyHitBox,
    MeteorEnemyHitBox,
    RegularEnemyHitBox,
    EnemyAmmo,
    Collectables,
}
