public enum CollisionLayers
{
    Enviroment = 1,
    Player,
    WordEnemy,
    MeteorEnemy,
    RegularEnemy,
    WordEnemyHurtBox,
    MeteorEnemyHurtBox,
    RegularEnemyHurtBox,
    PlayerRegularHurtBox,
    PlayerSpecialHurtBox,
    PlayerHitBox ,
    PlayerShieldHitBox,
    WordEnemyHitBox,
    MeteorEnemyHitBox,
    RegularEnemyHitBox,
    Collectables,
    PlayerCollectionArea,
}
